variables:
  KT_IMAGE: ${BUILD_IMAGE}
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
  WITH_SERVICE_DEPLOY: "true"

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

kt-test:
  image: $KT_IMAGE
  stage: test
  before_script:
    - ./test-instance/svdb-srv --demo-mode &
  script:
    - ./gradlew test
