include:
  - '/ci_templates/tasks.yml'

variables:
  KT_IMAGE: ${BUILD_IMAGE}
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: /certs/client
  WITH_SERVICE_DEPLOY: "true"

stages:
  - check
  - test

