// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/field.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package codes.spectrum.svdb.model.v1;

@kotlin.jvm.JvmName("-initializefield")
public inline fun field(block: codes.spectrum.svdb.model.v1.FieldKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.FieldOuterClass.Field =
  codes.spectrum.svdb.model.v1.FieldKt.Dsl._create(codes.spectrum.svdb.model.v1.FieldOuterClass.Field.newBuilder()).apply { block() }._build()
/**
 * ```
 * Field - описатель значения одного поля для кортежей
 * ```
 *
 * Protobuf type `codes.spectrum.svdb.model.v1.Field`
 */
public object FieldKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: codes.spectrum.svdb.model.v1.FieldOuterClass.Field.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: codes.spectrum.svdb.model.v1.FieldOuterClass.Field.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): codes.spectrum.svdb.model.v1.FieldOuterClass.Field = _builder.build()

    /**
     * ```
     * code - код поля
     * ```
     *
     * `string code = 10;`
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * ```
     * code - код поля
     * ```
     *
     * `string code = 10;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * value - значение поля
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value value = 20;`
     */
    public var value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * ```
     * value - значение поля
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value value = 20;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * value - значение поля
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value value = 20;`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
    public val FieldKt.Dsl.valueOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.FieldOuterClass.Field.copy(block: `codes.spectrum.svdb.model.v1`.FieldKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.FieldOuterClass.Field =
  `codes.spectrum.svdb.model.v1`.FieldKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val codes.spectrum.svdb.model.v1.FieldOuterClass.FieldOrBuilder.valueOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value?
  get() = if (hasValue()) getValue() else null

