// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package codes.spectrum.svdb.model.v1;

@kotlin.jvm.JvmName("-initializequeryOptions")
public inline fun queryOptions(block: codes.spectrum.svdb.model.v1.QueryOptionsKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions =
  codes.spectrum.svdb.model.v1.QueryOptionsKt.Dsl._create(codes.spectrum.svdb.model.v1.Query.QueryOptions.newBuilder()).apply { block() }._build()
/**
 * ```
 * клиентский запрос для SVDB
 * обертка над строкой в формате
 * встроенного языка SdQL
 * с поддержкой дополнительных параметров
 * ```
 *
 * Protobuf type `codes.spectrum.svdb.model.v1.QueryOptions`
 */
public object QueryOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): codes.spectrum.svdb.model.v1.Query.QueryOptions = _builder.build()

    /**
     * ```
     * текст запроса в формате SdQL
     * ```
     *
     * `string text = 1;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * ```
     * текст запроса в формате SdQL
     * ```
     *
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArgHeadsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     */
     public val argHeads: com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.argHeadsList
      )
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     * @param value The argHeads to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addArgHeads")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.add(value: codes.spectrum.svdb.model.v1.ColumnOuterClass.Column) {
      _builder.addArgHeads(value)
    }
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     * @param value The argHeads to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignArgHeads")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.plusAssign(value: codes.spectrum.svdb.model.v1.ColumnOuterClass.Column) {
      add(value)
    }
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     * @param values The argHeads to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllArgHeads")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.addAll(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column>) {
      _builder.addAllArgHeads(values)
    }
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     * @param values The argHeads to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllArgHeads")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.plusAssign(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column>) {
      addAll(values)
    }
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     * @param index The index to set the value at.
     * @param value The argHeads to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setArgHeads")
    public operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.set(index: kotlin.Int, value: codes.spectrum.svdb.model.v1.ColumnOuterClass.Column) {
      _builder.setArgHeads(index, value)
    }
    /**
     * ```
     * column описание аргумента
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Column argHeads = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearArgHeads")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ColumnOuterClass.Column, ArgHeadsProxy>.clear() {
      _builder.clearArgHeads()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArgValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     */
     public val argValues: com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.argValuesList
      )
    /**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     * @param value The argValues to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addArgValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.add(value: com.google.protobuf.ByteString) {
      _builder.addArgValues(value)
    }/**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     * @param value The argValues to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignArgValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.plusAssign(value: com.google.protobuf.ByteString) {
      add(value)
    }/**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     * @param values The argValues to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllArgValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      _builder.addAllArgValues(values)
    }/**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     * @param values The argValues to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllArgValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      addAll(values)
    }/**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     * @param index The index to set the value at.
     * @param value The argValues to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setArgValues")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.set(index: kotlin.Int, value: com.google.protobuf.ByteString) {
      _builder.setArgValues(index, value)
    }/**
     * ```
     * byteRecord - значение аргумента
     * ```
     *
     * `repeated bytes argValues = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearArgValues")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, ArgValuesProxy>.clear() {
      _builder.clearArgValues()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.Query.QueryOptions.copy(block: `codes.spectrum.svdb.model.v1`.QueryOptionsKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions =
  `codes.spectrum.svdb.model.v1`.QueryOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

