// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package codes.spectrum.svdb.model.v1;

@kotlin.jvm.JvmName("-initializequeryOptions")
public inline fun queryOptions(block: codes.spectrum.svdb.model.v1.QueryOptionsKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions =
  codes.spectrum.svdb.model.v1.QueryOptionsKt.Dsl._create(codes.spectrum.svdb.model.v1.Query.QueryOptions.newBuilder()).apply { block() }._build()
/**
 * ```
 * клиентский запрос для SVDB
 * пока это просто обертка над строкой в формате 
 * встроенного языка SdQL
 * NOTE: структура - чтобы не было простых типов в API,
 * под расширение
 * ```
 *
 * Protobuf type `codes.spectrum.svdb.model.v1.QueryOptions`
 */
public object QueryOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): codes.spectrum.svdb.model.v1.Query.QueryOptions = _builder.build()

    /**
     * ```
     * текст запроса в формате SdQL
     * ```
     *
     * `string text = 10;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * ```
     * текст запроса в формате SdQL
     * ```
     *
     * `string text = 10;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * режим выполнения запроса
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.QueryOptions.Mode mode = 20;`
     */
    public var mode: codes.spectrum.svdb.model.v1.Query.QueryOptions.Mode
      @JvmName("getMode")
      get() = _builder.getMode()
      @JvmName("setMode")
      set(value) {
        _builder.setMode(value)
      }
    public var modeValue: kotlin.Int
      @JvmName("getModeValue")
      get() = _builder.getModeValue()
      @JvmName("setModeValue")
      set(value) {
        _builder.setModeValue(value)
      }
    /**
     * ```
     * режим выполнения запроса
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.QueryOptions.Mode mode = 20;`
     */
    public fun clearMode() {
      _builder.clearMode()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArgsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     */
     public val args: com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getArgsList()
      )
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArgs")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.add(value: codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg) {
      _builder.addArgs(value)
    }
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.plusAssign(value: codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg) {
      add(value)
    }
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArgs")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.addAll(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg>) {
      _builder.addAllArgs(values)
    }
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.plusAssign(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg>) {
      addAll(values)
    }
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     * @param index The index to set the value at.
     * @param value The args to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArgs")
    public operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.set(index: kotlin.Int, value: codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg) {
      _builder.setArgs(index, value)
    }
    /**
     * `repeated .codes.spectrum.svdb.model.v1.QueryOptions.Arg args = 30;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArgs")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg, ArgsProxy>.clear() {
      _builder.clearArgs()
    }

  }
  @kotlin.jvm.JvmName("-initializearg")
  public inline fun arg(block: codes.spectrum.svdb.model.v1.QueryOptionsKt.ArgKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg =
    codes.spectrum.svdb.model.v1.QueryOptionsKt.ArgKt.Dsl._create(codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `codes.spectrum.svdb.model.v1.QueryOptions.Arg`
   */
  public object ArgKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg = _builder.build()

      /**
       * `.codes.spectrum.svdb.model.v1.DataType dataType = 5;`
       */
      public var dataType: codes.spectrum.svdb.model.v1.ColumnOuterClass.DataType
        @JvmName("getDataType")
        get() = _builder.getDataType()
        @JvmName("setDataType")
        set(value) {
          _builder.setDataType(value)
        }
      public var dataTypeValue: kotlin.Int
        @JvmName("getDataTypeValue")
        get() = _builder.getDataTypeValue()
        @JvmName("setDataTypeValue")
        set(value) {
          _builder.setDataTypeValue(value)
        }
      /**
       * `.codes.spectrum.svdb.model.v1.DataType dataType = 5;`
       */
      public fun clearDataType() {
        _builder.clearDataType()
      }

      /**
       * `string name = 10;`
       */
      public var name: kotlin.String
        @JvmName("getName")
        get() = _builder.getName()
        @JvmName("setName")
        set(value) {
          _builder.setName(value)
        }
      /**
       * `string name = 10;`
       */
      public fun clearName() {
        _builder.clearName()
      }

      /**
       * `.codes.spectrum.svdb.model.v1.Value value = 20;`
       */
      public var value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value
        @JvmName("getValue")
        get() = _builder.getValue()
        @JvmName("setValue")
        set(value) {
          _builder.setValue(value)
        }
      /**
       * `.codes.spectrum.svdb.model.v1.Value value = 20;`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
      /**
       * `.codes.spectrum.svdb.model.v1.Value value = 20;`
       * @return Whether the value field is set.
       */
      public fun hasValue(): kotlin.Boolean {
        return _builder.hasValue()
      }
      public val ArgKt.Dsl.valueOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value?
        get() = _builder.valueOrNull
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.Query.QueryOptions.copy(block: `codes.spectrum.svdb.model.v1`.QueryOptionsKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions =
  `codes.spectrum.svdb.model.v1`.QueryOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg.copy(block: `codes.spectrum.svdb.model.v1`.QueryOptionsKt.ArgKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.Query.QueryOptions.Arg =
  `codes.spectrum.svdb.model.v1`.QueryOptionsKt.ArgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val codes.spectrum.svdb.model.v1.Query.QueryOptions.ArgOrBuilder.valueOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value?
  get() = if (hasValue()) getValue() else null

