// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/record.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package codes.spectrum.svdb.model.v1;

@kotlin.jvm.JvmName("-initializerecord")
public inline fun record(block: codes.spectrum.svdb.model.v1.RecordKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.RecordOuterClass.Record =
  codes.spectrum.svdb.model.v1.RecordKt.Dsl._create(codes.spectrum.svdb.model.v1.RecordOuterClass.Record.newBuilder()).apply { block() }._build()
/**
 * ```
 * Описатель кортежа данных, под развитие
 * ```
 *
 * Protobuf type `codes.spectrum.svdb.model.v1.Record`
 */
public object RecordKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: codes.spectrum.svdb.model.v1.RecordOuterClass.Record.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: codes.spectrum.svdb.model.v1.RecordOuterClass.Record.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): codes.spectrum.svdb.model.v1.RecordOuterClass.Record = _builder.build()

    /**
     * ```
     * описатель происхождения кортежа, пока формат неопределен
     * например это может быть имя таблицы или номер запроса
     * или все вместе, пока считаем что это некая полуструктурированная
     * reference - строка
     * ```
     *
     * `string from = 10;`
     */
    public var from: kotlin.String
      @JvmName("getFrom")
      get() = _builder.getFrom()
      @JvmName("setFrom")
      set(value) {
        _builder.setFrom(value)
      }
    /**
     * ```
     * описатель происхождения кортежа, пока формат неопределен
     * например это может быть имя таблицы или номер запроса
     * или все вместе, пока считаем что это некая полуструктурированная
     * reference - строка
     * ```
     *
     * `string from = 10;`
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * ```
     * порядковый номер в курсоре
     * ```
     *
     * `int64 number = 11;`
     */
    public var number: kotlin.Long
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * ```
     * порядковый номер в курсоре
     * ```
     *
     * `int64 number = 11;`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FieldsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     */
     public val fields: com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFieldsList()
      )
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     * @param value The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFields")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.add(value: codes.spectrum.svdb.model.v1.FieldOuterClass.Field) {
      _builder.addFields(value)
    }
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     * @param value The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.plusAssign(value: codes.spectrum.svdb.model.v1.FieldOuterClass.Field) {
      add(value)
    }
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     * @param values The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFields")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.addAll(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.FieldOuterClass.Field>) {
      _builder.addAllFields(values)
    }
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     * @param values The fields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.plusAssign(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.FieldOuterClass.Field>) {
      addAll(values)
    }
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     * @param index The index to set the value at.
     * @param value The fields to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFields")
    public operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.set(index: kotlin.Int, value: codes.spectrum.svdb.model.v1.FieldOuterClass.Field) {
      _builder.setFields(index, value)
    }
    /**
     * ```
     * сами данные кортежа, карта между строкой и любым типом
     * используем документационную, а не реляционную модель по умолчанию,
     * так как класс данных тяготеет к разнородности в одном запросе
     * и к гетерогенным схемам
     * NOTE: возможно потом будут какие-то вариации, но пока именно полный формат
     * NOTE: как вариант конечно можно рассмотреть map<string, string> 
     * с упаковкой любых типов в string, но посмотрм сначала как себя
     * поведет ANY
     * ```
     *
     * `repeated .codes.spectrum.svdb.model.v1.Field fields = 20;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFields")
    public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.FieldOuterClass.Field, FieldsProxy>.clear() {
      _builder.clearFields()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.RecordOuterClass.Record.copy(block: `codes.spectrum.svdb.model.v1`.RecordKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.RecordOuterClass.Record =
  `codes.spectrum.svdb.model.v1`.RecordKt.Dsl._create(this.toBuilder()).apply { block() }._build()

