// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/value.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package codes.spectrum.svdb.model.v1;

@kotlin.jvm.JvmName("-initializevalue")
public inline fun value(block: codes.spectrum.svdb.model.v1.ValueKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value =
  codes.spectrum.svdb.model.v1.ValueKt.Dsl._create(codes.spectrum.svdb.model.v1.ValueOuterClass.Value.newBuilder()).apply { block() }._build()
/**
 * ```
 * JSON образный Any, фиксированный по типам
 * не используется google Any, так как очень избыточный
 * ```
 *
 * Protobuf type `codes.spectrum.svdb.model.v1.Value`
 */
public object ValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): codes.spectrum.svdb.model.v1.ValueOuterClass.Value = _builder.build()

    /**
     * ```
     * str - строчное значение
     * ```
     *
     * `string str = 10;`
     */
    public var str: kotlin.String
      @JvmName("getStr")
      get() = _builder.getStr()
      @JvmName("setStr")
      set(value) {
        _builder.setStr(value)
      }
    /**
     * ```
     * str - строчное значение
     * ```
     *
     * `string str = 10;`
     */
    public fun clearStr() {
      _builder.clearStr()
    }
    /**
     * ```
     * str - строчное значение
     * ```
     *
     * `string str = 10;`
     * @return Whether the str field is set.
     */
    public fun hasStr(): kotlin.Boolean {
      return _builder.hasStr()
    }

    /**
     * ```
     * i32 - int (int32)
     * ```
     *
     * `int32 i32 = 12;`
     */
    public var i32: kotlin.Int
      @JvmName("getI32")
      get() = _builder.getI32()
      @JvmName("setI32")
      set(value) {
        _builder.setI32(value)
      }
    /**
     * ```
     * i32 - int (int32)
     * ```
     *
     * `int32 i32 = 12;`
     */
    public fun clearI32() {
      _builder.clearI32()
    }
    /**
     * ```
     * i32 - int (int32)
     * ```
     *
     * `int32 i32 = 12;`
     * @return Whether the i32 field is set.
     */
    public fun hasI32(): kotlin.Boolean {
      return _builder.hasI32()
    }

    /**
     * ```
     * i64 - long (int64)
     * ```
     *
     * `int64 i64 = 20;`
     */
    public var i64: kotlin.Long
      @JvmName("getI64")
      get() = _builder.getI64()
      @JvmName("setI64")
      set(value) {
        _builder.setI64(value)
      }
    /**
     * ```
     * i64 - long (int64)
     * ```
     *
     * `int64 i64 = 20;`
     */
    public fun clearI64() {
      _builder.clearI64()
    }
    /**
     * ```
     * i64 - long (int64)
     * ```
     *
     * `int64 i64 = 20;`
     * @return Whether the i64 field is set.
     */
    public fun hasI64(): kotlin.Boolean {
      return _builder.hasI64()
    }

    /**
     * ```
     * double - double (float64)
     * ```
     *
     * `double f64 = 30;`
     */
    public var f64: kotlin.Double
      @JvmName("getF64")
      get() = _builder.getF64()
      @JvmName("setF64")
      set(value) {
        _builder.setF64(value)
      }
    /**
     * ```
     * double - double (float64)
     * ```
     *
     * `double f64 = 30;`
     */
    public fun clearF64() {
      _builder.clearF64()
    }
    /**
     * ```
     * double - double (float64)
     * ```
     *
     * `double f64 = 30;`
     * @return Whether the f64 field is set.
     */
    public fun hasF64(): kotlin.Boolean {
      return _builder.hasF64()
    }

    /**
     * ```
     * типа Decimal
     * ```
     *
     * `string dec = 35;`
     */
    public var dec: kotlin.String
      @JvmName("getDec")
      get() = _builder.getDec()
      @JvmName("setDec")
      set(value) {
        _builder.setDec(value)
      }
    /**
     * ```
     * типа Decimal
     * ```
     *
     * `string dec = 35;`
     */
    public fun clearDec() {
      _builder.clearDec()
    }
    /**
     * ```
     * типа Decimal
     * ```
     *
     * `string dec = 35;`
     * @return Whether the dec field is set.
     */
    public fun hasDec(): kotlin.Boolean {
      return _builder.hasDec()
    }

    /**
     * ```
     * bit - 1/0, boolean (bool),  NOTE: название такое, чтобы 3 символа было как у всех
     * ```
     *
     * `bool bit = 40;`
     */
    public var bit: kotlin.Boolean
      @JvmName("getBit")
      get() = _builder.getBit()
      @JvmName("setBit")
      set(value) {
        _builder.setBit(value)
      }
    /**
     * ```
     * bit - 1/0, boolean (bool),  NOTE: название такое, чтобы 3 символа было как у всех
     * ```
     *
     * `bool bit = 40;`
     */
    public fun clearBit() {
      _builder.clearBit()
    }
    /**
     * ```
     * bit - 1/0, boolean (bool),  NOTE: название такое, чтобы 3 символа было как у всех
     * ```
     *
     * `bool bit = 40;`
     * @return Whether the bit field is set.
     */
    public fun hasBit(): kotlin.Boolean {
      return _builder.hasBit()
    }

    /**
     * ```
     * obj - вложенный сложный объект
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Obj obj = 50;`
     */
    public var obj: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj
      @JvmName("getObj")
      get() = _builder.getObj()
      @JvmName("setObj")
      set(value) {
        _builder.setObj(value)
      }
    /**
     * ```
     * obj - вложенный сложный объект
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Obj obj = 50;`
     */
    public fun clearObj() {
      _builder.clearObj()
    }
    /**
     * ```
     * obj - вложенный сложный объект
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Obj obj = 50;`
     * @return Whether the obj field is set.
     */
    public fun hasObj(): kotlin.Boolean {
      return _builder.hasObj()
    }

    /**
     * ```
     * arr - вложенная коллекция
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Arr arr = 60;`
     */
    public var arr: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr
      @JvmName("getArr")
      get() = _builder.getArr()
      @JvmName("setArr")
      set(value) {
        _builder.setArr(value)
      }
    /**
     * ```
     * arr - вложенная коллекция
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Arr arr = 60;`
     */
    public fun clearArr() {
      _builder.clearArr()
    }
    /**
     * ```
     * arr - вложенная коллекция
     * ```
     *
     * `.codes.spectrum.svdb.model.v1.Value.Arr arr = 60;`
     * @return Whether the arr field is set.
     */
    public fun hasArr(): kotlin.Boolean {
      return _builder.hasArr()
    }

    /**
     * ```
     * dur - строчное значение duration
     * ```
     *
     * `string dur = 70;`
     */
    public var dur: kotlin.String
      @JvmName("getDur")
      get() = _builder.getDur()
      @JvmName("setDur")
      set(value) {
        _builder.setDur(value)
      }
    /**
     * ```
     * dur - строчное значение duration
     * ```
     *
     * `string dur = 70;`
     */
    public fun clearDur() {
      _builder.clearDur()
    }
    /**
     * ```
     * dur - строчное значение duration
     * ```
     *
     * `string dur = 70;`
     * @return Whether the dur field is set.
     */
    public fun hasDur(): kotlin.Boolean {
      return _builder.hasDur()
    }

    /**
     * ```
     * tim - строчное значение time
     * ```
     *
     * `string tim = 80;`
     */
    public var tim: kotlin.String
      @JvmName("getTim")
      get() = _builder.getTim()
      @JvmName("setTim")
      set(value) {
        _builder.setTim(value)
      }
    /**
     * ```
     * tim - строчное значение time
     * ```
     *
     * `string tim = 80;`
     */
    public fun clearTim() {
      _builder.clearTim()
    }
    /**
     * ```
     * tim - строчное значение time
     * ```
     *
     * `string tim = 80;`
     * @return Whether the tim field is set.
     */
    public fun hasTim(): kotlin.Boolean {
      return _builder.hasTim()
    }
    public val valueCase: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.ValueCase
      @JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
  @kotlin.jvm.JvmName("-initializeobj")
  public inline fun obj(block: codes.spectrum.svdb.model.v1.ValueKt.ObjKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj =
    codes.spectrum.svdb.model.v1.ValueKt.ObjKt.Dsl._create(codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Obj структура - враппер для передачи сложных объектов
   * ```
   *
   * Protobuf type `codes.spectrum.svdb.model.v1.Value.Obj`
   */
  public object ObjKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ObjProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
       public val obj: com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getObjMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getObjMap()
        )
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
      @JvmName("putObj")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        .put(key: kotlin.String, value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value) {
           _builder.putObj(key, value)
         }
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setObj")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        .set(key: kotlin.String, value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value) {
           put(key, value)
         }
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeObj")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        .remove(key: kotlin.String) {
           _builder.removeObj(key)
         }
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllObj")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value>) {
           _builder.putAllObj(map)
         }
      /**
       * ```
       * obj - карта строка - вложенное значение
       * ```
       *
       * `map<string, .codes.spectrum.svdb.model.v1.Value> obj = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearObj")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ObjProxy>
        .clear() {
           _builder.clearObj()
         }
    }
  }
  @kotlin.jvm.JvmName("-initializearr")
  public inline fun arr(block: codes.spectrum.svdb.model.v1.ValueKt.ArrKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr =
    codes.spectrum.svdb.model.v1.ValueKt.ArrKt.Dsl._create(codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Arr структура - враппер для передачи массивов
   * ```
   *
   * Protobuf type `codes.spectrum.svdb.model.v1.Value.Arr`
   */
  public object ArrKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ArrProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       */
       public val arr: com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getArrList()
        )
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       * @param value The arr to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addArr")
      public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.add(value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value) {
        _builder.addArr(value)
      }
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       * @param value The arr to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignArr")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.plusAssign(value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value) {
        add(value)
      }
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       * @param values The arr to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllArr")
      public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.addAll(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.ValueOuterClass.Value>) {
        _builder.addAllArr(values)
      }
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       * @param values The arr to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllArr")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.plusAssign(values: kotlin.collections.Iterable<codes.spectrum.svdb.model.v1.ValueOuterClass.Value>) {
        addAll(values)
      }
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       * @param index The index to set the value at.
       * @param value The arr to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setArr")
      public operator fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.set(index: kotlin.Int, value: codes.spectrum.svdb.model.v1.ValueOuterClass.Value) {
        _builder.setArr(index, value)
      }
      /**
       * ```
       * arr - коллекция значений
       * ```
       *
       * `repeated .codes.spectrum.svdb.model.v1.Value arr = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearArr")
      public fun com.google.protobuf.kotlin.DslList<codes.spectrum.svdb.model.v1.ValueOuterClass.Value, ArrProxy>.clear() {
        _builder.clearArr()
      }

    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.ValueOuterClass.Value.copy(block: `codes.spectrum.svdb.model.v1`.ValueKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value =
  `codes.spectrum.svdb.model.v1`.ValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj.copy(block: `codes.spectrum.svdb.model.v1`.ValueKt.ObjKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj =
  `codes.spectrum.svdb.model.v1`.ValueKt.ObjKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr.copy(block: `codes.spectrum.svdb.model.v1`.ValueKt.ArrKt.Dsl.() -> kotlin.Unit): codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr =
  `codes.spectrum.svdb.model.v1`.ValueKt.ArrKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder.objOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Obj?
  get() = if (hasObj()) getObj() else null

public val codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder.arrOrNull: codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Arr?
  get() = if (hasArr()) getArr() else null

