FROM openjdk:17.0.2-slim-buster

RUN set -x \
    && apt update \
    && apt -y install zip unzip \
    && adduser --disabled-password \
        --home "/nonexistent" \
        --no-create-home \
        --uid "10001" \
        --gecos "" \
        "appuser"

USER appuser:appuser

COPY --chown=appuser:appuser  ./test_instance/svdb-srv /opt/svdb-srv