// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/byte_record.proto
// Protobuf Java Version: 4.27.3

package codes.spectrum.svdb.model.v1;

public final class ByteRecordOuterClass {
  private ByteRecordOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ByteRecordOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ByteRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codes.spectrum.svdb.model.v1.ByteRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> 
        getFieldsList();
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getFields(int index);
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    int getFieldsCount();
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    java.util.List<? extends codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder getFieldsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * запись с полями в виде байтов
   * </pre>
   *
   * Protobuf type {@code codes.spectrum.svdb.model.v1.ByteRecord}
   */
  public static final class ByteRecord extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:codes.spectrum.svdb.model.v1.ByteRecord)
      ByteRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        ByteRecord.class.getName());
    }
    // Use ByteRecord.newBuilder() to construct.
    private ByteRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ByteRecord() {
      fields_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.class, codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.Builder.class);
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> fields_;
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    @java.lang.Override
    public java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> getFieldsList() {
      return fields_;
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    @java.lang.Override
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
     */
    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(1, fields_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fields_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord)) {
        return super.equals(obj);
      }
      codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord other = (codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord) obj;

      if (!getFieldsList()
          .equals(other.getFieldsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * запись с полями в виде байтов
     * </pre>
     *
     * Protobuf type {@code codes.spectrum.svdb.model.v1.ByteRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codes.spectrum.svdb.model.v1.ByteRecord)
        codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.class, codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.Builder.class);
      }

      // Construct using codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
        } else {
          fields_ = null;
          fieldsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord getDefaultInstanceForType() {
        return codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.getDefaultInstance();
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord build() {
        codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord buildPartial() {
        codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord result = new codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord result) {
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
      }

      private void buildPartial0(codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord) {
          return mergeFrom((codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord other) {
        if (other == codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord.getDefaultInstance()) return this;
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField m =
                    input.readMessage(
                        codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.parser(),
                        extensionRegistry);
                if (fieldsBuilder_ == null) {
                  ensureFieldsIsMutable();
                  fields_.add(m);
                } else {
                  fieldsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fields_ = new java.util.ArrayList<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField>(fields_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder> fieldsBuilder_;

      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder setFields(
          int index, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder setFields(
          int index, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder addFields(codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder addFields(
          int index, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder addFields(
          codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder addFields(
          int index, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public java.util.List<? extends codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.getDefaultInstance());
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.getDefaultInstance());
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated .codes.spectrum.svdb.model.v1.ByteField fields = 1;</code>
       */
      public java.util.List<codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:codes.spectrum.svdb.model.v1.ByteRecord)
    }

    // @@protoc_insertion_point(class_scope:codes.spectrum.svdb.model.v1.ByteRecord)
    private static final codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord();
    }

    public static codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ByteRecord>
        PARSER = new com.google.protobuf.AbstractParser<ByteRecord>() {
      @java.lang.Override
      public ByteRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ByteRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ByteRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ByteRecordOuterClass.ByteRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codes_spectrum_svdb_model_v1_ByteRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024v1/byte_record.proto\022\034codes.spectrum.s" +
      "vdb.model.v1\032\023v1/byte_field.proto\"E\n\nByt" +
      "eRecord\0227\n\006fields\030\001 \003(\0132\'.codes.spectrum" +
      ".svdb.model.v1.ByteFieldB/Z-gitlab.spect" +
      "rumdata.tech/sd3/svdb/go/model/v1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          codes.spectrum.svdb.model.v1.ByteFieldOuterClass.getDescriptor(),
        });
    internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codes_spectrum_svdb_model_v1_ByteRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codes_spectrum_svdb_model_v1_ByteRecord_descriptor,
        new java.lang.String[] { "Fields", });
    descriptor.resolveAllFeaturesImmutable();
    codes.spectrum.svdb.model.v1.ByteFieldOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
