// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/byte_field.proto
// Protobuf Java Version: 4.27.3

package codes.spectrum.svdb.model.v1;

public final class ByteFieldOuterClass {
  private ByteFieldOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ByteFieldOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ByteFieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codes.spectrum.svdb.model.v1.ByteField)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * значение поля в виде массива байтов
     * </pre>
     *
     * <code>bytes item = 1;</code>
     * @return The item.
     */
    com.google.protobuf.ByteString getItem();

    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @return A list containing the items.
     */
    java.util.List<com.google.protobuf.ByteString> getItemsList();
    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @return The count of items.
     */
    int getItemsCount();
    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @param index The index of the element to return.
     * @return The items at the given index.
     */
    com.google.protobuf.ByteString getItems(int index);
  }
  /**
   * <pre>
   * поле
   * </pre>
   *
   * Protobuf type {@code codes.spectrum.svdb.model.v1.ByteField}
   */
  public static final class ByteField extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:codes.spectrum.svdb.model.v1.ByteField)
      ByteFieldOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        ByteField.class.getName());
    }
    // Use ByteField.newBuilder() to construct.
    private ByteField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ByteField() {
      item_ = com.google.protobuf.ByteString.EMPTY;
      items_ = emptyList(com.google.protobuf.ByteString.class);
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.class, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder.class);
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString item_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * значение поля в виде массива байтов
     * </pre>
     *
     * <code>bytes item = 1;</code>
     * @return The item.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getItem() {
      return item_;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> items_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @return A list containing the items.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getItemsList() {
      return items_;
    }
    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @return The count of items.
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <pre>
     * не используется, будет DEPRECATED в версии 2.0
     * </pre>
     *
     * <code>repeated bytes items = 2;</code>
     * @param index The index of the element to return.
     * @return The items at the given index.
     */
    public com.google.protobuf.ByteString getItems(int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!item_.isEmpty()) {
        output.writeBytes(1, item_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeBytes(2, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!item_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, item_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < items_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(items_.get(i));
        }
        size += dataSize;
        size += 1 * getItemsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField)) {
        return super.equals(obj);
      }
      codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField other = (codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField) obj;

      if (!getItem()
          .equals(other.getItem())) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getItem().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * поле
     * </pre>
     *
     * Protobuf type {@code codes.spectrum.svdb.model.v1.ByteField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codes.spectrum.svdb.model.v1.ByteField)
        codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.class, codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.Builder.class);
      }

      // Construct using codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        item_ = com.google.protobuf.ByteString.EMPTY;
        items_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getDefaultInstanceForType() {
        return codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.getDefaultInstance();
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField build() {
        codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField buildPartial() {
        codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField result = new codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.item_ = item_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          items_.makeImmutable();
          result.items_ = items_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField) {
          return mergeFrom((codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField other) {
        if (other == codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField.getDefaultInstance()) return this;
        if (other.getItem() != com.google.protobuf.ByteString.EMPTY) {
          setItem(other.getItem());
        }
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            items_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                item_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureItemsIsMutable();
                items_.add(v);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString item_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * значение поля в виде массива байтов
       * </pre>
       *
       * <code>bytes item = 1;</code>
       * @return The item.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getItem() {
        return item_;
      }
      /**
       * <pre>
       * значение поля в виде массива байтов
       * </pre>
       *
       * <code>bytes item = 1;</code>
       * @param value The item to set.
       * @return This builder for chaining.
       */
      public Builder setItem(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        item_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * значение поля в виде массива байтов
       * </pre>
       *
       * <code>bytes item = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearItem() {
        bitField0_ = (bitField0_ & ~0x00000001);
        item_ = getDefaultInstance().getItem();
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> items_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureItemsIsMutable() {
        if (!items_.isModifiable()) {
          items_ = makeMutableCopy(items_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @return A list containing the items.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getItemsList() {
        items_.makeImmutable();
        return items_;
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @return The count of items.
       */
      public int getItemsCount() {
        return items_.size();
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @param index The index of the element to return.
       * @return The items at the given index.
       */
      public com.google.protobuf.ByteString getItems(int index) {
        return items_.get(index);
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @param index The index to set the value at.
       * @param value The items to set.
       * @return This builder for chaining.
       */
      public Builder setItems(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureItemsIsMutable();
        items_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @param value The items to add.
       * @return This builder for chaining.
       */
      public Builder addItems(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureItemsIsMutable();
        items_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @param values The items to add.
       * @return This builder for chaining.
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * не используется, будет DEPRECATED в версии 2.0
       * </pre>
       *
       * <code>repeated bytes items = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItems() {
        items_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:codes.spectrum.svdb.model.v1.ByteField)
    }

    // @@protoc_insertion_point(class_scope:codes.spectrum.svdb.model.v1.ByteField)
    private static final codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField();
    }

    public static codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ByteField>
        PARSER = new com.google.protobuf.AbstractParser<ByteField>() {
      @java.lang.Override
      public ByteField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ByteField> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ByteField> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ByteFieldOuterClass.ByteField getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codes_spectrum_svdb_model_v1_ByteField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023v1/byte_field.proto\022\034codes.spectrum.sv" +
      "db.model.v1\"(\n\tByteField\022\014\n\004item\030\001 \001(\014\022\r" +
      "\n\005items\030\002 \003(\014B/Z-gitlab.spectrumdata.tec" +
      "h/sd3/svdb/go/model/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codes_spectrum_svdb_model_v1_ByteField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codes_spectrum_svdb_model_v1_ByteField_descriptor,
        new java.lang.String[] { "Item", "Items", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
