// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/fetch.proto
// Protobuf Java Version: 4.31.1

package codes.spectrum.svdb.model.v1;

@com.google.protobuf.Generated
public final class Fetch {
  private Fetch() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Fetch.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FetchOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codes.spectrum.svdb.model.v1.FetchOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
     * </pre>
     *
     * <code>string cursorUid = 1;</code>
     * @return The cursorUid.
     */
    java.lang.String getCursorUid();
    /**
     * <pre>
     * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
     * </pre>
     *
     * <code>string cursorUid = 1;</code>
     * @return The bytes for cursorUid.
     */
    com.google.protobuf.ByteString
        getCursorUidBytes();

    /**
     * <pre>
     * режим выполнения запроса
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
     * @return The enum numeric value on the wire for mode.
     */
    int getModeValue();
    /**
     * <pre>
     * режим выполнения запроса
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
     * @return The mode.
     */
    codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode getMode();
  }
  /**
   * <pre>
   * клиентский запрос для SVDB
   * пока это просто обертка над строкой в формате 
   * встроенного языка SdQL
   * NOTE: структура - чтобы не было простых типов в API,
   * под расширение
   * </pre>
   *
   * Protobuf type {@code codes.spectrum.svdb.model.v1.FetchOptions}
   */
  public static final class FetchOptions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:codes.spectrum.svdb.model.v1.FetchOptions)
      FetchOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        FetchOptions.class.getName());
    }
    // Use FetchOptions.newBuilder() to construct.
    private FetchOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FetchOptions() {
      cursorUid_ = "";
      mode_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codes.spectrum.svdb.model.v1.Fetch.internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codes.spectrum.svdb.model.v1.Fetch.internal_static_codes_spectrum_svdb_model_v1_FetchOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codes.spectrum.svdb.model.v1.Fetch.FetchOptions.class, codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Builder.class);
    }

    /**
     * <pre>
     * режим выполнения запроса
     * </pre>
     *
     * Protobuf enum {@code codes.spectrum.svdb.model.v1.FetchOptions.Mode}
     */
    public enum Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * один фетч батч размера от 1 до N
       * </pre>
       *
       * <code>ONE = 0;</code>
       */
      ONE(0),
      /**
       * <pre>
       * все записи - режим для fetchAll
       * </pre>
       *
       * <code>ALL = 1;</code>
       */
      ALL(1),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 31,
          /* patch= */ 1,
          /* suffix= */ "",
          Mode.class.getName());
      }
      /**
       * <pre>
       * один фетч батч размера от 1 до N
       * </pre>
       *
       * <code>ONE = 0;</code>
       */
      public static final int ONE_VALUE = 0;
      /**
       * <pre>
       * все записи - режим для fetchAll
       * </pre>
       *
       * <code>ALL = 1;</code>
       */
      public static final int ALL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Mode valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Mode forNumber(int value) {
        switch (value) {
          case 0: return ONE;
          case 1: return ALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Mode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
              public Mode findValueByNumber(int number) {
                return Mode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.Fetch.FetchOptions.getDescriptor().getEnumTypes().get(0);
      }

      private static final Mode[] VALUES = values();

      public static Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Mode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:codes.spectrum.svdb.model.v1.FetchOptions.Mode)
    }

    public static final int CURSORUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cursorUid_ = "";
    /**
     * <pre>
     * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
     * </pre>
     *
     * <code>string cursorUid = 1;</code>
     * @return The cursorUid.
     */
    @java.lang.Override
    public java.lang.String getCursorUid() {
      java.lang.Object ref = cursorUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cursorUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
     * </pre>
     *
     * <code>string cursorUid = 1;</code>
     * @return The bytes for cursorUid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCursorUidBytes() {
      java.lang.Object ref = cursorUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursorUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODE_FIELD_NUMBER = 2;
    private int mode_ = 0;
    /**
     * <pre>
     * режим выполнения запроса
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <pre>
     * режим выполнения запроса
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
     * @return The mode.
     */
    @java.lang.Override public codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode getMode() {
      codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode result = codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.forNumber(mode_);
      return result == null ? codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cursorUid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, cursorUid_);
      }
      if (mode_ != codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.ONE.getNumber()) {
        output.writeEnum(2, mode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cursorUid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, cursorUid_);
      }
      if (mode_ != codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.ONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof codes.spectrum.svdb.model.v1.Fetch.FetchOptions)) {
        return super.equals(obj);
      }
      codes.spectrum.svdb.model.v1.Fetch.FetchOptions other = (codes.spectrum.svdb.model.v1.Fetch.FetchOptions) obj;

      if (!getCursorUid()
          .equals(other.getCursorUid())) return false;
      if (mode_ != other.mode_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURSORUID_FIELD_NUMBER;
      hash = (53 * hash) + getCursorUid().hashCode();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + mode_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(codes.spectrum.svdb.model.v1.Fetch.FetchOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * клиентский запрос для SVDB
     * пока это просто обертка над строкой в формате 
     * встроенного языка SdQL
     * NOTE: структура - чтобы не было простых типов в API,
     * под расширение
     * </pre>
     *
     * Protobuf type {@code codes.spectrum.svdb.model.v1.FetchOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codes.spectrum.svdb.model.v1.FetchOptions)
        codes.spectrum.svdb.model.v1.Fetch.FetchOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.Fetch.internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codes.spectrum.svdb.model.v1.Fetch.internal_static_codes_spectrum_svdb_model_v1_FetchOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codes.spectrum.svdb.model.v1.Fetch.FetchOptions.class, codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Builder.class);
      }

      // Construct using codes.spectrum.svdb.model.v1.Fetch.FetchOptions.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cursorUid_ = "";
        mode_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codes.spectrum.svdb.model.v1.Fetch.internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.Fetch.FetchOptions getDefaultInstanceForType() {
        return codes.spectrum.svdb.model.v1.Fetch.FetchOptions.getDefaultInstance();
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.Fetch.FetchOptions build() {
        codes.spectrum.svdb.model.v1.Fetch.FetchOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.Fetch.FetchOptions buildPartial() {
        codes.spectrum.svdb.model.v1.Fetch.FetchOptions result = new codes.spectrum.svdb.model.v1.Fetch.FetchOptions(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(codes.spectrum.svdb.model.v1.Fetch.FetchOptions result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cursorUid_ = cursorUid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mode_ = mode_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codes.spectrum.svdb.model.v1.Fetch.FetchOptions) {
          return mergeFrom((codes.spectrum.svdb.model.v1.Fetch.FetchOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codes.spectrum.svdb.model.v1.Fetch.FetchOptions other) {
        if (other == codes.spectrum.svdb.model.v1.Fetch.FetchOptions.getDefaultInstance()) return this;
        if (!other.getCursorUid().isEmpty()) {
          cursorUid_ = other.cursorUid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.mode_ != 0) {
          setModeValue(other.getModeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                cursorUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                mode_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object cursorUid_ = "";
      /**
       * <pre>
       * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
       * </pre>
       *
       * <code>string cursorUid = 1;</code>
       * @return The cursorUid.
       */
      public java.lang.String getCursorUid() {
        java.lang.Object ref = cursorUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cursorUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
       * </pre>
       *
       * <code>string cursorUid = 1;</code>
       * @return The bytes for cursorUid.
       */
      public com.google.protobuf.ByteString
          getCursorUidBytes() {
        java.lang.Object ref = cursorUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cursorUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
       * </pre>
       *
       * <code>string cursorUid = 1;</code>
       * @param value The cursorUid to set.
       * @return This builder for chaining.
       */
      public Builder setCursorUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cursorUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
       * </pre>
       *
       * <code>string cursorUid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursorUid() {
        cursorUid_ = getDefaultInstance().getCursorUid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uid курсора, который нужно фетчить. если пусто, то фетчится последний курсор
       * </pre>
       *
       * <code>string cursorUid = 1;</code>
       * @param value The bytes for cursorUid to set.
       * @return This builder for chaining.
       */
      public Builder setCursorUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cursorUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int mode_ = 0;
      /**
       * <pre>
       * режим выполнения запроса
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
       * @return The enum numeric value on the wire for mode.
       */
      @java.lang.Override public int getModeValue() {
        return mode_;
      }
      /**
       * <pre>
       * режим выполнения запроса
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
       * @param value The enum numeric value on the wire for mode to set.
       * @return This builder for chaining.
       */
      public Builder setModeValue(int value) {
        mode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * режим выполнения запроса
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
       * @return The mode.
       */
      @java.lang.Override
      public codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode getMode() {
        codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode result = codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.forNumber(mode_);
        return result == null ? codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * режим выполнения запроса
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(codes.spectrum.svdb.model.v1.Fetch.FetchOptions.Mode value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        mode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * режим выполнения запроса
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.FetchOptions.Mode mode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:codes.spectrum.svdb.model.v1.FetchOptions)
    }

    // @@protoc_insertion_point(class_scope:codes.spectrum.svdb.model.v1.FetchOptions)
    private static final codes.spectrum.svdb.model.v1.Fetch.FetchOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new codes.spectrum.svdb.model.v1.Fetch.FetchOptions();
    }

    public static codes.spectrum.svdb.model.v1.Fetch.FetchOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchOptions>
        PARSER = new com.google.protobuf.AbstractParser<FetchOptions>() {
      @java.lang.Override
      public FetchOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FetchOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public codes.spectrum.svdb.model.v1.Fetch.FetchOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codes_spectrum_svdb_model_v1_FetchOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016v1/fetch.proto\022\034codes.spectrum.svdb.mo" +
      "del.v1\"z\n\014FetchOptions\022\021\n\tcursorUid\030\001 \001(" +
      "\t\022=\n\004mode\030\002 \001(\0162/.codes.spectrum.svdb.mo" +
      "del.v1.FetchOptions.Mode\"\030\n\004Mode\022\007\n\003ONE\020" +
      "\000\022\007\n\003ALL\020\001B/Z-gitlab.spectrumdata.tech/s" +
      "d3/svdb/go/model/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codes_spectrum_svdb_model_v1_FetchOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codes_spectrum_svdb_model_v1_FetchOptions_descriptor,
        new java.lang.String[] { "CursorUid", "Mode", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
