// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/field.proto
// Protobuf Java Version: 4.27.3

package codes.spectrum.svdb.model.v1;

public final class FieldOuterClass {
  private FieldOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      FieldOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codes.spectrum.svdb.model.v1.Field)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * code - код поля
     * </pre>
     *
     * <code>string code = 10;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <pre>
     * code - код поля
     * </pre>
     *
     * <code>string code = 10;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     * @return The value.
     */
    codes.spectrum.svdb.model.v1.ValueOuterClass.Value getValue();
    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     */
    codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder getValueOrBuilder();
  }
  /**
   * <pre>
   * Field - описатель значения одного поля для кортежей
   * </pre>
   *
   * Protobuf type {@code codes.spectrum.svdb.model.v1.Field}
   */
  public static final class Field extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:codes.spectrum.svdb.model.v1.Field)
      FieldOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        Field.class.getName());
    }
    // Use Field.newBuilder() to construct.
    private Field(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Field() {
      code_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codes.spectrum.svdb.model.v1.FieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_Field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codes.spectrum.svdb.model.v1.FieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codes.spectrum.svdb.model.v1.FieldOuterClass.Field.class, codes.spectrum.svdb.model.v1.FieldOuterClass.Field.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object code_ = "";
    /**
     * <pre>
     * code - код поля
     * </pre>
     *
     * <code>string code = 10;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * code - код поля
     * </pre>
     *
     * <code>string code = 10;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 20;
    private codes.spectrum.svdb.model.v1.ValueOuterClass.Value value_;
    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     * @return The value.
     */
    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ValueOuterClass.Value getValue() {
      return value_ == null ? codes.spectrum.svdb.model.v1.ValueOuterClass.Value.getDefaultInstance() : value_;
    }
    /**
     * <pre>
     * value - значение поля
     * </pre>
     *
     * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
     */
    @java.lang.Override
    public codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder getValueOrBuilder() {
      return value_ == null ? codes.spectrum.svdb.model.v1.ValueOuterClass.Value.getDefaultInstance() : value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, code_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(20, getValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, code_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof codes.spectrum.svdb.model.v1.FieldOuterClass.Field)) {
        return super.equals(obj);
      }
      codes.spectrum.svdb.model.v1.FieldOuterClass.Field other = (codes.spectrum.svdb.model.v1.FieldOuterClass.Field) obj;

      if (!getCode()
          .equals(other.getCode())) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(codes.spectrum.svdb.model.v1.FieldOuterClass.Field prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Field - описатель значения одного поля для кортежей
     * </pre>
     *
     * Protobuf type {@code codes.spectrum.svdb.model.v1.Field}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codes.spectrum.svdb.model.v1.Field)
        codes.spectrum.svdb.model.v1.FieldOuterClass.FieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.FieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_Field_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codes.spectrum.svdb.model.v1.FieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_Field_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codes.spectrum.svdb.model.v1.FieldOuterClass.Field.class, codes.spectrum.svdb.model.v1.FieldOuterClass.Field.Builder.class);
      }

      // Construct using codes.spectrum.svdb.model.v1.FieldOuterClass.Field.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = "";
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codes.spectrum.svdb.model.v1.FieldOuterClass.internal_static_codes_spectrum_svdb_model_v1_Field_descriptor;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.FieldOuterClass.Field getDefaultInstanceForType() {
        return codes.spectrum.svdb.model.v1.FieldOuterClass.Field.getDefaultInstance();
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.FieldOuterClass.Field build() {
        codes.spectrum.svdb.model.v1.FieldOuterClass.Field result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.FieldOuterClass.Field buildPartial() {
        codes.spectrum.svdb.model.v1.FieldOuterClass.Field result = new codes.spectrum.svdb.model.v1.FieldOuterClass.Field(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(codes.spectrum.svdb.model.v1.FieldOuterClass.Field result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = valueBuilder_ == null
              ? value_
              : valueBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codes.spectrum.svdb.model.v1.FieldOuterClass.Field) {
          return mergeFrom((codes.spectrum.svdb.model.v1.FieldOuterClass.Field)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codes.spectrum.svdb.model.v1.FieldOuterClass.Field other) {
        if (other == codes.spectrum.svdb.model.v1.FieldOuterClass.Field.getDefaultInstance()) return this;
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 82: {
                code_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 82
              case 162: {
                input.readMessage(
                    getValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 162
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <pre>
       * code - код поля
       * </pre>
       *
       * <code>string code = 10;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * code - код поля
       * </pre>
       *
       * <code>string code = 10;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * code - код поля
       * </pre>
       *
       * <code>string code = 10;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * code - код поля
       * </pre>
       *
       * <code>string code = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = getDefaultInstance().getCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * code - код поля
       * </pre>
       *
       * <code>string code = 10;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private codes.spectrum.svdb.model.v1.ValueOuterClass.Value value_;
      private com.google.protobuf.SingleFieldBuilder<
          codes.spectrum.svdb.model.v1.ValueOuterClass.Value, codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder, codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder> valueBuilder_;
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       * @return The value.
       */
      public codes.spectrum.svdb.model.v1.ValueOuterClass.Value getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? codes.spectrum.svdb.model.v1.ValueOuterClass.Value.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public Builder setValue(codes.spectrum.svdb.model.v1.ValueOuterClass.Value value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
        } else {
          valueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public Builder setValue(
          codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public Builder mergeValue(codes.spectrum.svdb.model.v1.ValueOuterClass.Value value) {
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            value_ != null &&
            value_ != codes.spectrum.svdb.model.v1.ValueOuterClass.Value.getDefaultInstance()) {
            getValueBuilder().mergeFrom(value);
          } else {
            value_ = value;
          }
        } else {
          valueBuilder_.mergeFrom(value);
        }
        if (value_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder getValueBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      public codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              codes.spectrum.svdb.model.v1.ValueOuterClass.Value.getDefaultInstance() : value_;
        }
      }
      /**
       * <pre>
       * value - значение поля
       * </pre>
       *
       * <code>.codes.spectrum.svdb.model.v1.Value value = 20;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          codes.spectrum.svdb.model.v1.ValueOuterClass.Value, codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder, codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              codes.spectrum.svdb.model.v1.ValueOuterClass.Value, codes.spectrum.svdb.model.v1.ValueOuterClass.Value.Builder, codes.spectrum.svdb.model.v1.ValueOuterClass.ValueOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:codes.spectrum.svdb.model.v1.Field)
    }

    // @@protoc_insertion_point(class_scope:codes.spectrum.svdb.model.v1.Field)
    private static final codes.spectrum.svdb.model.v1.FieldOuterClass.Field DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new codes.spectrum.svdb.model.v1.FieldOuterClass.Field();
    }

    public static codes.spectrum.svdb.model.v1.FieldOuterClass.Field getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Field>
        PARSER = new com.google.protobuf.AbstractParser<Field>() {
      @java.lang.Override
      public Field parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Field> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Field> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public codes.spectrum.svdb.model.v1.FieldOuterClass.Field getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codes_spectrum_svdb_model_v1_Field_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codes_spectrum_svdb_model_v1_Field_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016v1/field.proto\022\034codes.spectrum.svdb.mo" +
      "del.v1\032\016v1/value.proto\"I\n\005Field\022\014\n\004code\030" +
      "\n \001(\t\0222\n\005value\030\024 \001(\0132#.codes.spectrum.sv" +
      "db.model.v1.ValueB/Z-gitlab.spectrumdata" +
      ".tech/sd3/svdb/go/model/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          codes.spectrum.svdb.model.v1.ValueOuterClass.getDescriptor(),
        });
    internal_static_codes_spectrum_svdb_model_v1_Field_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codes_spectrum_svdb_model_v1_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codes_spectrum_svdb_model_v1_Field_descriptor,
        new java.lang.String[] { "Code", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    codes.spectrum.svdb.model.v1.ValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
