// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/record.proto

package codes.spectrum.svdb.model.v1;

public final class RecordOuterClass {
  private RecordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codes.spectrum.svdb.model.v1.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @return A list containing the fields.
     */
    java.util.List<com.google.protobuf.ByteString> getFieldsList();
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @return The count of fields.
     */
    int getFieldsCount();
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @param index The index of the element to return.
     * @return The fields at the given index.
     */
    com.google.protobuf.ByteString getFields(int index);
  }
  /**
   * <pre>
   * запись с полями в виде байтов
   * </pre>
   *
   * Protobuf type {@code codes.spectrum.svdb.model.v1.Record}
   */
  public static final class Record extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:codes.spectrum.svdb.model.v1.Record)
      RecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Record() {
      fields_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Record();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codes.spectrum.svdb.model.v1.RecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_Record_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codes.spectrum.svdb.model.v1.RecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codes.spectrum.svdb.model.v1.RecordOuterClass.Record.class, codes.spectrum.svdb.model.v1.RecordOuterClass.Record.Builder.class);
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.ByteString> fields_;
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @return A list containing the fields.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getFieldsList() {
      return fields_;
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @return The count of fields.
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <pre>
     * поля в виде байтов
     * </pre>
     *
     * <code>repeated bytes fields = 1;</code>
     * @param index The index of the element to return.
     * @return The fields at the given index.
     */
    public com.google.protobuf.ByteString getFields(int index) {
      return fields_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fields_.size(); i++) {
        output.writeBytes(1, fields_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fields_.get(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof codes.spectrum.svdb.model.v1.RecordOuterClass.Record)) {
        return super.equals(obj);
      }
      codes.spectrum.svdb.model.v1.RecordOuterClass.Record other = (codes.spectrum.svdb.model.v1.RecordOuterClass.Record) obj;

      if (!getFieldsList()
          .equals(other.getFieldsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(codes.spectrum.svdb.model.v1.RecordOuterClass.Record prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * запись с полями в виде байтов
     * </pre>
     *
     * Protobuf type {@code codes.spectrum.svdb.model.v1.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codes.spectrum.svdb.model.v1.Record)
        codes.spectrum.svdb.model.v1.RecordOuterClass.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codes.spectrum.svdb.model.v1.RecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_Record_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codes.spectrum.svdb.model.v1.RecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codes.spectrum.svdb.model.v1.RecordOuterClass.Record.class, codes.spectrum.svdb.model.v1.RecordOuterClass.Record.Builder.class);
      }

      // Construct using codes.spectrum.svdb.model.v1.RecordOuterClass.Record.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fields_ = java.util.Collections.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codes.spectrum.svdb.model.v1.RecordOuterClass.internal_static_codes_spectrum_svdb_model_v1_Record_descriptor;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.RecordOuterClass.Record getDefaultInstanceForType() {
        return codes.spectrum.svdb.model.v1.RecordOuterClass.Record.getDefaultInstance();
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.RecordOuterClass.Record build() {
        codes.spectrum.svdb.model.v1.RecordOuterClass.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public codes.spectrum.svdb.model.v1.RecordOuterClass.Record buildPartial() {
        codes.spectrum.svdb.model.v1.RecordOuterClass.Record result = new codes.spectrum.svdb.model.v1.RecordOuterClass.Record(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(codes.spectrum.svdb.model.v1.RecordOuterClass.Record result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
      }

      private void buildPartial0(codes.spectrum.svdb.model.v1.RecordOuterClass.Record result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codes.spectrum.svdb.model.v1.RecordOuterClass.Record) {
          return mergeFrom((codes.spectrum.svdb.model.v1.RecordOuterClass.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codes.spectrum.svdb.model.v1.RecordOuterClass.Record other) {
        if (other == codes.spectrum.svdb.model.v1.RecordOuterClass.Record.getDefaultInstance()) return this;
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureFieldsIsMutable();
                fields_.add(v);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> fields_ = java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fields_ = new java.util.ArrayList<com.google.protobuf.ByteString>(fields_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @return A list containing the fields.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getFieldsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(fields_) : fields_;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @return The count of fields.
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @param index The index of the element to return.
       * @return The fields at the given index.
       */
      public com.google.protobuf.ByteString getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @param index The index to set the value at.
       * @param value The fields to set.
       * @return This builder for chaining.
       */
      public Builder setFields(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @param value The fields to add.
       * @return This builder for chaining.
       */
      public Builder addFields(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @param values The fields to add.
       * @return This builder for chaining.
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * поля в виде байтов
       * </pre>
       *
       * <code>repeated bytes fields = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFields() {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:codes.spectrum.svdb.model.v1.Record)
    }

    // @@protoc_insertion_point(class_scope:codes.spectrum.svdb.model.v1.Record)
    private static final codes.spectrum.svdb.model.v1.RecordOuterClass.Record DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new codes.spectrum.svdb.model.v1.RecordOuterClass.Record();
    }

    public static codes.spectrum.svdb.model.v1.RecordOuterClass.Record getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Record>
        PARSER = new com.google.protobuf.AbstractParser<Record>() {
      @java.lang.Override
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Record> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public codes.spectrum.svdb.model.v1.RecordOuterClass.Record getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codes_spectrum_svdb_model_v1_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codes_spectrum_svdb_model_v1_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017v1/record.proto\022\034codes.spectrum.svdb.m" +
      "odel.v1\"\030\n\006Record\022\016\n\006fields\030\001 \003(\014B/Z-git" +
      "lab.spectrumdata.tech/sd3/svdb/go/model/" +
      "v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_codes_spectrum_svdb_model_v1_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codes_spectrum_svdb_model_v1_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codes_spectrum_svdb_model_v1_Record_descriptor,
        new java.lang.String[] { "Fields", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
