name: tests
on:
  push:
  workflow_dispatch:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container:
      image: avtocod/svdb-jdbc-test:0.0.1
      options: --user root
      volumes:
        - /opt:/test_instance
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v4'
      - name: 'Setup kotlin'
        uses: 'fwilhe2/setup-kotlin@main'
      - name: 'Tests'
        run: './gradlew test'
      - name: 'Build step'
        run: './gradlew :jdbc:fatJar'
